#server:
#  port: 9002
#spring:
#  application:
#    name: tensquare-recruit #指定服务名
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.80.130:3306/tensquare_recruit?characterEncoding=UTF8
#    username: root
#    password: root
#  jpa:
#    database: MySQL
#    show-sql: true
#  data:
#    mongodb:
#      host: 192.168.80.130
#      database: recruitdb
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:6868/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
