server:
  port: 9013
spring:
  application:
    name: tensquare-web #指定服务名
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
    register-with-eureka: true #因为该应用为注册中心，不会注册自己
    fetch-registry: true #是否需要从eureka上获取注册信息
  instance:
    prefer-ip-address: true
#zuul网关服务
zuul:
  routes:
    #用户微服务
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
    #招聘微服务
    tensquare-recruit:
      path: /recruit/**
      serviceId: tensquare-recruit
    tensquare-enterprise:
      path: /enterprise/**
      serviceId: tensquare-recruit
    #吐槽微服务
    tensquare-spit:
      path: /spit/**
      serviceId: tensquare-spit
    #问答微服务
    tensquare-qa:
      path: /label/**
      serviceId: tensquare-qa
    tensquare-reply:
      path: /reply/**
      serviceId: tensquare-qa
    tensquare-problem:
      path: /problem/**
      serviceId: tensquare-qa
    #基础微服务
    tensquare-base:
      path: /label/**
      serviceId: tensquare-base
    #活动微服务
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    #文章微服务
    tensquare-article:
      path: /article/**
      serviceId: tensquare-article
    tensquare-channel:
      path: /channel/**
      serviceId: tensquare-article
    tensquare-column:
      path: /column/**
      serviceId: tensquare-article
    tensquare-comment:
      path: /comment/**
      serviceId: tensquare-article