#server:
#  port: 9003
#spring:
#  application:
#    name: tensquare-qa #指定服务名
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.80.130:3306/tensquare_qa?characterEncoding=UTF8
#    username: root
#    password: root
#  data:
#    mongodb:
#      host: 192.168.80.130:27017
#      database: qadb
#  jpa:
#    database: MySQL
#    show-sql: true
#jwt:
#  config:
#    key: kongqi #jwt加盐
#    ttl: 360000 #token过期时间
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:6868/eureka/
#  instance:
#    prefer-ip-address: true
#
##开启网关
#feign:
#  hystrix:
#    enabled: true
